# Generated by Django 4.1.7 on 2025-05-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chat_id_telegram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='medicion',
            name='caff',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
