# Generated by Django 4.1.7 on 2026-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrol',
            options={'verbose_name': 'Asignar rol', 'verbose_name_plural': 'Asignar roles'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='archivos/archivos_useravatar/'),
        ),
    ]
