# Generated by Django 4.1.7 on 2026-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0002_alter_userrol_options_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
